<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://kit.fontawesome.com/96a458c9a5.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <!-- start header -->
        <header class="header banner">
            <div class="">
                <nav>
                    <div class="logo"><a href="index.php"> Blog </a></div>
                    
                   
                    <div class="register hide nav-list">
                    <ul class="list-register">
                    <li><a href="index.php">Home</a></li>
                            <?php if(isset($_SESSION['user'])):?>
                                <?php if($_SESSION['user']['admin']==1):?>
                                    
                                <li><a href="admin/dashboard.php" ><i class="fas fa-user"></i> <?=$_SESSION['user']['username']?></a></li>
                                <?php else:?>   
                                    <li><a href="user/dashboard.php"><i class="fas fa-user"></i> <?=$_SESSION['user']['username']?></a></li>
                                <?php endif;?>
                                <li><i class="fas fa-sign-in-alt"></i> <a href="logout.php">disconnect</a></li>
                                
                                <?php else:?>
                            <li><i class="fas fa-sign-in-alt"></i> <a href="sign_up.php"> Sign Up</a></li>
                            <li><i class="fas fa-user"></i> <a href="sign_in.php"> Sign In</a></li>
                            <?php endif;?>
                                

                               
                               
                          
                              
                        </ul>
                    </div>
                    
                    <div class="toggle"><i class="fas fa-bars" hidden></i></div>
                </nav>
             
            </div>
          
        </header>

        <main class="self-artcile">
        <article class="artcile ">   

        <div class="full">
      
        <img  src="<?=$baseUrl."/images/postsImages/".$articles['image']?>" alt="">
      <div class="container">
    
     
      <h2> <?=$articles['titre']?> </h2>
      <p class="description-categorie"> <?=$articles['description']?> <p class="date">   <?=$articles['date']?> </p> </p>
      </div>
    </div>
        
     
        </article>
                              

                                    <article class="comment">
                                    
                                        <form action="" method="POST">
                                      
                                        <div>
                                            <textarea id="" cols="30" rows="10" placeholder="Your Comment ........" name="comment"></textarea>
                                            <button name="post_comment">Comment</button>
                                            </div>
                                        </form>
                                
                                        <?php foreach ($comments as $comment):?>
                                        <div class=comment-user>
                                      
                                          <div class="user-info">  
                                        <img src="images/avatar.png" alt="">
                                        <label for=""><?=$comment['pseudo']?></label>
                                        <span><?=dateFormate($comment['date_comment'])?></span>
                                        <?php if(isset($_SESSION['user'])): ?>
                                            <?php if ($comment['pseudo']==$_SESSION['user']['username']):?>
                                        <a href=<?= "deleteCommentArticle.php?postId=" . $_GET['id'] ."&id=" . $comment['id']?>><i class="fas fa-trash"></i></a>
                                        <?php endif ;?>
                                        <?php endif ;?>
                                        </div>
                                        <p><?=$comment['comment']?></p>
                                        </div>
                                    
                                        <?php endforeach ;?>
                               
                                    </article>

        </main>