<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://kit.fontawesome.com/96a458c9a5.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="<?=$baseUrl."/css/style.css"?>">
</head>
<body>
    <!-- start header -->
        <header class="header banner">
            <div class="">
                <nav>
                    <div class="logo"><a href="index.php"> Blog </a></div>
                    
                
                    <div class="register hide nav-list">
                    <ul class="list-register">
                    <li><a href="index.php">Home</a></li>
                            <?php if(isset($_SESSION['user'])):?>
                                
                                <?php if($_SESSION['user']['admin']==1):?>
                                    
                                <li><a href="admin/dashboard.php" ><i class="fas fa-user"></i> <?=$_SESSION['user']['username']?></a></li>
                                <?php else:?>   
                                    <li><a href="user/dashboard.php"><i class="fas fa-user"></i> <?=$_SESSION['user']['username']?></a></li>
                                <?php endif;?>
                                <li><i class="fas fa-sign-in-alt"></i> <a href="logout.php">disconnect</a></li>
                                
                                <?php else:?>
                            <li><i class="fas fa-sign-in-alt"></i> <a href="sign_up.php"> Sign Up</a></li>
                            <li><i class="fas fa-user"></i> <a href="sign_in.php"> Sign In</a></li>
                            <?php endif;?>
                                

                               
                               
                          
                              
                        </ul>
                    </div>
                    
                    <div class="toggle"><i class="fas fa-bars" hidden></i></div>
                </nav>
             
            </div>
          
        </header>
    <!-- end header -->
    
    
    <!-- start main  -->

    <main class="main-home">
  
    <section>
  
        <ul class="categories">
        <h2>Categories of articles</h2>
        
          <?php foreach ($resCategories as $category): ?>
          
          <li><a href=""><?= $category['categorie']?> ( <?=coutCategories($category['categorie'])?>) </a></li>
          <?php endforeach ;?>
        </ul>

    </section>  

    <section>
    <article class="artcile">   
        
    <?php foreach ($articles as $article):?>                                
   

    <div class="card">
    <h2 class="Categorie"><?=$article['categorie']?></h2>
    <img src="<?=$baseUrl."images/postsImages/".$article['image']?>" alt="">
  <div class="container">

  
  <h3><?=$article['titre']?></h3>
  <p><?= readMore($article['description'],150) ?></p>
  <div class="readMore">
        <a href="article.php?id=<?=$article[0]?>">Read More</a>
       <span><?=$article['date']?></span>
       </div> 
  </div>
</div>
    

        
    <?php endforeach ; ?>
 
    </article>
        
    </section> 
    
  


    </main>




    <!-- end main  -->

    <script src="js/main.js "></script>
</body>
</html>