<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://kit.fontawesome.com/96a458c9a5.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <!-- start header -->
        <header class="header banner">
            <div class="">
                <nav>
                    <div class="logo"><a href="index.php"> Blog </a></div>
                    
                    <div class="menu hide nav-list">
                        <ul>
                            <li><a href="index.php">Home</a></li>
                            <li><a href="">About</a></li>
                            <li><a href="">Services</a></li>
                            <li><a href="">Contact</a></li>
                        </ul>
                    </div>
                    <div class="register hide nav-list">
                    <ul class="list-register">
                       
                            <?php if(isset($_SESSION['user'])):?>
                                <?php if($_SESSION['user']['admin']==1):?>
                                    
                                <li><a href="admin/dashboard.php"><i class="fas fa-user"></i> <?=$_SESSION['user']['username']?></a></li>
                                <?php else:?>   
                                    <li><a href="user/dashboard.php"><i class="fas fa-user"></i> <?=$_SESSION['user']['username']?></a></li>
                                <?php endif;?>
                                <li><i class="fas fa-sign-in-alt"></i> <a href="logout.php">disconnect</a></li>
                                
                                <?php else:?>
                            <li><i class="fas fa-sign-in-alt"></i> <a href="sign_up.php"> Sign Up</a></li>
                            <li><i class="fas fa-user"></i> <a href="sign_in.php"> Sign In</a></li>
                            <?php endif;?>
                                

                               
                               
                          
                              
                        </ul>
                    </div>
                    
                    <div class="toggle"><i class="fas fa-bars" hidden></i></div>
                </nav>
             
            </div>
          
        </header>
    <!-- end header -->


    <script src="js/main.js "></script>
</body>
</html>