<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://kit.fontawesome.com/96a458c9a5.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css/style.css">
</head>
<body class="connect">
    <!-- start header -->
        <header>
            <div class="">
                <nav>
                    <div class="logo"><a href="index.php"> Blog </a></div>
                    
                    <div class="menu hide nav-list">
                        <ul>
                            <li><a href="index.php">Home</a></li>
                            <li><a href="">About</a></li>
                            <li><a href="">Services</a></li>
                            <li><a href="">Contact</a></li>
                        </ul>
                    </div>
                    <div class="register hide nav-list">
                    <ul class="list-register">
                            <li><i class="fas fa-sign-in-alt"></i> <a href="sign_up.php"> Sign Up</a></li>
                            <li><i class="fas fa-user"></i> <a href="sign_in.php"> Sign In</a></li>
                            
                        </ul>
                    </div>
                    
                    <div class="toggle"><i class="fas fa-bars" hidden></i></div>
                </nav>
             
            </div>
          
        </header>
    <!-- end header -->

    <main>
        <div class="flush-message"><?php flushmessage() ;?>
        <?php unset($_SESSION['flush'])?>
        </div>
    <div class="contact-form">
        <img src="images/avatar.png" alt="avatar" class="avatar">
        <h2>Sign In</h2>

        <form action="" method="post">
        <?php if(isset($error['login'])) :?><div class="errors"><?=$error['login']?></div>
         
         <?php endif;?>

            <label for="">Email</label>
            <input type="email" placeholder="Enter Email" name="email" required=""> 
            <label for="">Password</label>
            <input type="password" placeholder="Enter Password" name="password" required="">
            <button class="btn-sign-in"type="submit" name="login">Sign in</button>
        </form>
    </div>

    </main>


    <script src="js/main.js "></script>
</body>
</html>