<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://kit.fontawesome.com/96a458c9a5.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../css/admin.css">
</head>

<body>
    <!-- start header -->
    <div class="container">
        <div class="navigation">
            <ul>
                <li>
                    <a href="dashboard.php">
                        <span class="icon"><i class="fas fa-tachometer-alt"></i></span>
                        <span class="title">
                            <h2>dashboard</h2>
                        </span>
                    </a>
                </li>

                <li>
                    <a href="../index.php">
                        <span class="icon"><i class="fas fa-home"></i></span>
                        <span class="title">Home</span>
                    </a>
                </li>

                <li>
                    <a href="">
                        <span class="icon"><i class="fas fa-user"></i></span>
                        <span class="title">Users</span>
                    </a>
                </li>
                <li>
                    <a href="categories.php">
                        <span class="icon"><i class="fas fa-bible"></i></span>
                        <span class="title">Add Categories</span>
                    </a>
                </li>
                <li>
                    <a href="">
                        <span class="icon"><i class="far fa-newspaper"></i></span>
                        <span class="title">Add Article</span>
                    </a>
                </li>
                <li>
                    <a href="">
                        <span class="icon"><i class="far fa-comments"></i></span>
                        <span class="title">Comments</span>
                    </a>
                </li>
                <li>
                    <a href="../logout.php">
                        <span class="icon"><i class="fas fa-sign-out-alt"></i></span>
                        <span class="title">Logout</span>
                    </a>
                </li>

            </ul>
        </div>
        <!--end header  -->

        <div class="main">
            <div class="topbar">
                <div class="toggle"></div>
                <div class="search">
                    <label for="">
                        <input type="text" placeholder="Search here">
                        <i class="fas fa-search"></i>
                    </label>
                </div>
                <div class="user">
                    <img src="../images/man.png" alt="Admin">
                    </span>
                </div>

                <?php if (isset($_SESSION['user'])) :  ?>
                    <span class="name"> <?= $_SESSION['user']['username'] ?>

                    <?php endif;  ?>
            </div>

                    <!-- start card BOX -->
            <div class="title">
                 
                            <div>
                                <h2>List Users</h2>

                                <table class="table-categories">
                                    <thead>
                                        <tr>
                                            <td>id</td>
                                            <td>email</td>
                                            <td>UserName</td>
                                            <td>Delete</td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    <?php if(empty($resUsers)):?>    
                                    <p>list Is empty</p>
                                    <?php endif; ?>
                                        <?php foreach ($resUsers as $user):?>
                  
                                            
                                        
                                         <tr>
                                             <td><?=$user['id']?></td>
                                             <td><?=$user['email']?></td>
                                             <td><?=$user['username']?></td>
                                             <td><a href="deleteUser.php?id=<?php echo $user['id'];?>"><i class="fas fa-trash"></i></a></td>
                                         </tr>
                                             
                                        <?php endforeach ; ?>    
                                    </tbody>
                                </table>
                            </div>
            </div>
    </div>
    </div>

    <script src="../js/dashborad.js"></script>
</body>

</html>